### ISSUE TITLE
Flicker when typing function arguments

### ISSUE THREAD

**Issue by smjonas** [simrat39/inlay-hints.nvim#2]
Hey, first of all thanks for this plugin, it has great potential!
Please have a look at a screen recording of my issue here:
![inlay_hints_flicker](https://user-images.githubusercontent.com/40792180/183241874-7babe904-adf2-4644-beaf-5daa97ba89c0.gif)

Is there a way to reduce the flicker? Seems like the inlay hint is not cached for the current line, is that correct? 

My configuration is as follows:
```lua
require("inlay-hints").setup {
  only_current_line = true
}
```

Also, a suggestion: could you maybe add a GIF showing how your plugin looks like in the readme :)

**Comment by simrat39** [comment]
We update the hints whenever the text changes, which makes it flicker, I think some kind of denouncing will probably help

**Comment by simrat39** [comment]
Do you have any repro for this? Can't seem to be able to reproduce it on my side

**Comment by smjonas** [comment]
Unfortunately, I don't have any reproduction steps other then typing anything in a function call in a Lua file. Maybe another plugin is causing problems but I checked `TextChanged` autocommands and there's nothing else except `nvim-cmp` (which I tried to disable - the issue remains) and the builtin `matchparen` plugin.

**Comment by simrat39** [comment]
Honestly I can't reproduce this on my side, will see if others have this problem and a repro pops up, and will work on a separate solution in the meanwhile

**Comment by simrat39** [comment]
Should be fixed now

**Comment by smjonas** [comment]
Unfortunately, it's still not fixed for me:
![inlay_hints_flicker2](https://user-images.githubusercontent.com/40792180/184310670-fe616007-e441-46b9-83f1-e50785545564.gif)
I am on the latest commit.

**Comment by simrat39** [comment]
What about now? Pretty sure it shouldn't redraw excessively now

**Comment by smjonas** [comment]
Still not fixed, sorry :smile: Thanks for all your efforts trying to fix this issue!

**Comment by simrat39** [comment]
Ok I tried your config (from your dotfiles) and still can't replicate it.
Could you tell me your
- neovim version
- if you are on the latest commit
- how you setup and use inlay hints

**Comment by simrat39** [comment]
Ok I can repro it now, seems like an issue with only_current_line

**Comment by simrat39** [comment]
Should be actually fixed now with https://github.com/simrat39/inlay-hints.nvim/commit/fa97742e8d45bac157a638bda7280671c9afa072

**Comment by smjonas** [comment]
Thank you so much, it is actually fixed now!
